CREATE TABLE IF NOT EXISTS `#__cwcontact_customfields` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(250) NOT NULL,
  `alias` varchar(250) NOT NULL,
  `type` varchar(100) NOT NULL,
  `options` mediumtext NOT NULL,
  `required` tinyint(4) NOT NULL,
  `params` text NOT NULL,
  `lbl` varchar(255) NOT NULL,
  `hint` varchar(255) NOT NULL,
  `warning` varchar(255) NOT NULL,
  `mod_ids` varchar(255) NOT NULL,
  `art_ids` varchar(255) NOT NULL,
  `state` tinyint(3) NOT NULL DEFAULT '0',
  `checked_out` int(10) unsigned NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created` datetime NOT NULL,
  `created_by` int(10) NOT NULL,
  `created_by_alias` varchar(255) NOT NULL,
  `modified` datetime NOT NULL,
  `modified_by` int(10) NOT NULL,
  `publish_up` datetime NOT NULL,
  `publish_down` datetime NOT NULL,
  `ordering` int(11) NOT NULL,
  `language` varchar(7) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;